[("400", "invalid input value"),
("403", "drive full"),
("405", "file not found"),
("406", "invalid file name"),
("407", "file already exists"),
("409", "fail to write the file"),
("410", "fail to open the file"),
("411", "fail to read the file"),
("417", "fail to list the file"),
("418", "fail to delete the file"),
("419", "fail to get disk info"),
("420", "no space"),
("421", "timeout"),
("423", "file too large"),
("425", "invalid parameter"),
("426", "file already opened"),
("751", "Unknown error"),
("752", "URL length error"),
("753", "URL error"),
("754", "Invalid proxy type"),
("755", "Proxy address error"),
("756", "Invalid parameter"),
("757", "Recipient address full"),
("758", "CC recipient address full"),
("759", "BCC recipient address full"),
("760", "Attachments full"),
("761", "File error"),
("762", "No recipient"),
("763", "File not found"),
("764", "MMS busy"),
("765", "Server response failed"),
("766", "Error response of HTTP(S) post"),
("767", "Invalid report of HTTP(S) post"),
("768", "PDP activation failed"),
("769", "PDP deactivated"),
("770", "Socket creation failed"),
("771", "Socket connection failed"),
("772", "Socket read failed"),
("773", "Socket write failed"),
("774", "Socket closed"),
("775", "Timeout"),
("776", "Encode data error"),
("777", "HTTP(S) decode data error")]